fe/src/components/TextInput/TextInput.stories.ts, fe/src/components/TextInput/TextInput.tsx, fe/src/components/TextInput/TextInputStyle.ts, fe/src/components/index.ts, fe/src/styles/GlobalStyle.ts, fe/src/styles/Typography.ts
=> [FE] TextInput 컴포넌트 추가

fe/pnpm-lock.yaml, fe/src/components/button/Button.stories.ts, fe/src/components/button/Button.tsx, fe/src/components/button/ButtonStyle.ts
=> [FE] Button 컴포넌트 구현

fe/src/App.tsx, fe/src/components/Icon/IconStyle.ts, fe/src/index.css, fe/src/styles/GlobalStyle.ts
폰트가 적용안되는 버그 수정하기 위해 index.css 파일 추가
* 작성하세요
=> [FE] 폰트 적용이 안되는 버그 수정

fe/src/App.tsx, fe/src/components/Icon/IconStyle.ts, fe/src/styles/GlobalStyle.ts, fe/src/styles/index.css
=> [FE] 아이콘 폰트 적용 버그 수정

BE/build.gradle, BE/src/main/java/codesquad/secondhand/SecondHandApplication.java, BE/src/main/java/codesquad/secondhand/config/JasyptConfig.java, BE/src/main/resources/application.yml, BE/src/test/java/codesquad/secondhand/SecondHandApplicationTests.java
=> [BE] Swagger 사용을 위한 초기 설정 및 패키지 명 수정

fe/src/components/commons/Button/Button.tsx, fe/src/components/commons/Button/ButtonStyle.ts, fe/src/components/commons/Icon/Icon.tsx, fe/src/components/commons/Icon/IconStyle.ts, fe/src/components/commons/NavBar/NavBar.tsx, fe/src/components/commons/Profile/Profile.tsx, fe/src/components/commons/Profile/ProfileStyle.ts, fe/src/components/commons/Tab/Tab.tsx, fe/src/components/commons/TextInput/TextInput.tsx, fe/src/components/commons/TextInput/TextInputStyle.ts, fe/src/styles/index.css
=> [FE] 1주차 피드백 반영

fe/.storybook/style.css, fe/public/index.html, fe/src/assets/icons/index.ts, fe/src/components/commons/BottomSheet/BottomSheet.stories.tsx, fe/src/components/commons/BottomSheet/BottomSheet.tsx, fe/src/components/commons/BottomSheet/BottomSheetStyle.ts, fe/src/components/commons/Button/Button.stories.ts, fe/src/components/commons/Button/Button.tsx, fe/src/components/commons/Button/ButtonStyle.ts, fe/src/components/commons/Icon/IconStyle.ts, fe/src/components/commons/TextInput/TextInput.tsx, fe/src/components/commons/TextInput/TextInputStyle.ts, fe/src/components/commons/index.ts, fe/src/styles/GlobalStyle.ts
=> [FE] BottomSheet 컴포넌트 추가

fe/.storybook/style.css, fe/src/assets/icons/index.ts, fe/src/components/commons/BottomSheet/BottomSheet.stories.tsx, fe/src/components/commons/BottomSheet/BottomSheet.tsx, fe/src/components/commons/BottomSheet/BottomSheetStyle.ts, fe/src/components/commons/Button/Button.stories.ts, fe/src/components/commons/Button/Button.tsx, fe/src/components/commons/Button/ButtonStyle.ts, fe/src/components/commons/Dialog/Dialog.stories.tsx, fe/src/components/commons/Dialog/Dialog.tsx, fe/src/components/commons/Dialog/DialogStyle.ts, fe/src/components/commons/Icon/IconStyle.ts, fe/src/components/commons/Tab/Tab.stories.tsx, fe/src/components/commons/TextInput/TextInput.tsx, fe/src/components/commons/TextInput/TextInputStyle.ts, fe/src/components/commons/index.ts, fe/src/styles/GlobalStyle.ts
=> [FE] Dialog 컴포넌트 추가

fe/.storybook/style.css, fe/src/assets/icons/index.ts, fe/src/components/commons/BottomSheet/BottomSheet.stories.tsx, fe/src/components/commons/BottomSheet/BottomSheet.tsx, fe/src/components/commons/BottomSheet/BottomSheetStyle.ts, fe/src/components/commons/Button/Button.stories.ts, fe/src/components/commons/Button/Button.tsx, fe/src/components/commons/Button/ButtonStyle.ts, fe/src/components/commons/Dialog/Dialog.stories.tsx, fe/src/components/commons/Dialog/Dialog.tsx, fe/src/components/commons/Dialog/DialogStyle.ts, fe/src/components/commons/Icon/IconStyle.ts, fe/src/components/commons/SnackBar/SnackBar.stories.tsx, fe/src/components/commons/SnackBar/SnackBar.tsx, fe/src/components/commons/SnackBar/SnackBarStyle.ts, fe/src/components/commons/Tab/Tab.stories.tsx, fe/src/components/commons/TextInput/TextInput.tsx, fe/src/components/commons/TextInput/TextInputStyle.ts, fe/src/components/commons/index.ts, fe/src/styles/GlobalStyle.ts
=> [FE] Snackbar 컴포넌트 추가

fe/.storybook/style.css, fe/src/assets/icons/index.ts, fe/src/components/commons/BottomSheet/BottomSheet.stories.tsx, fe/src/components/commons/BottomSheet/BottomSheet.tsx, fe/src/components/commons/BottomSheet/BottomSheetStyle.ts, fe/src/components/commons/Button/Button.stories.ts, fe/src/components/commons/Button/Button.tsx, fe/src/components/commons/Button/ButtonStyle.ts, fe/src/components/commons/Dialog/Dialog.stories.tsx, fe/src/components/commons/Dialog/Dialog.tsx, fe/src/components/commons/Dialog/DialogStyle.ts, fe/src/components/commons/Icon/IconStyle.ts, fe/src/components/commons/NavBar/NavBar.tsx, fe/src/components/commons/NavBar/NavBarStyle.ts, fe/src/components/commons/NavBar/Navbar.stories.tsx, fe/src/components/commons/SnackBar/SnackBar.stories.tsx, fe/src/components/commons/SnackBar/SnackBar.tsx, fe/src/components/commons/SnackBar/SnackBarStyle.ts, fe/src/components/commons/Tab/Tab.stories.tsx, fe/src/components/commons/Tab/Tab.tsx, fe/src/components/commons/TextInput/TextInput.tsx, fe/src/components/commons/TextInput/TextInputStyle.ts, fe/src/components/commons/index.ts, fe/src/styles/GlobalStyle.ts
=> [FE] Navber 컴포넌트 추가

fe/package.json, fe/pnpm-lock.yaml, fe/src/components/commons/ListItem/ListItem.tsx
=> [FE] Type 에러 및 의존성 문제 해결

fe/src/components/commons/BottomSheet/BottomSheet.tsx, fe/src/components/commons/NavBar/NavBar.tsx, fe/src/components/commons/Profile/Profile.tsx, fe/src/components/commons/SnackBar/SnackBar.tsx
=> [FE] FE -> DEV 병합

.github/workflows/be-aws.yml, fe/src/components/commons/BottomSheet/BottomSheet.tsx, fe/src/components/commons/NavBar/NavBar.tsx, fe/src/components/commons/Profile/Profile.tsx, fe/src/components/commons/SnackBar/SnackBar.tsx
=> [FE] Dev-> Main 병합

iOS/SecondHand/SecondHand.xcodeproj/project.pbxproj, iOS/SecondHand/SecondHand/Assets.xcassets/Colors/Contents.json, iOS/SecondHand/SecondHand/Assets.xcassets/Colors/black.colorset/Contents.json, iOS/SecondHand/SecondHand/Assets.xcassets/Colors/blue.colorset/Contents.json, iOS/SecondHand/SecondHand/Assets.xcassets/Colors/gray100.colorset/Contents.json, iOS/SecondHand/SecondHand/Assets.xcassets/Colors/gray200.colorset/Contents.json, iOS/SecondHand/SecondHand/Assets.xcassets/Colors/gray300.colorset/Contents.json, iOS/SecondHand/SecondHand/Assets.xcassets/Colors/gray400.colorset/Contents.json, iOS/SecondHand/SecondHand/Assets.xcassets/Colors/gray50.colorset/Contents.json, iOS/SecondHand/SecondHand/Assets.xcassets/Colors/gray500.colorset/Contents.json, iOS/SecondHand/SecondHand/Assets.xcassets/Colors/gray600.colorset/Contents.json, iOS/SecondHand/SecondHand/Assets.xcassets/Colors/gray700.colorset/Contents.json, iOS/SecondHand/SecondHand/Assets.xcassets/Colors/gray800.colorset/Contents.json, iOS/SecondHand/SecondHand/Assets.xcassets/Colors/gray900.colorset/Contents.json, iOS/SecondHand/SecondHand/Assets.xcassets/Colors/mint.colorset/Contents.json, iOS/SecondHand/SecondHand/Assets.xcassets/Colors/orange.colorset/Contents.json, iOS/SecondHand/SecondHand/Assets.xcassets/Colors/red.colorset/Contents.json, iOS/SecondHand/SecondHand/Assets.xcassets/Colors/white.colorset/Contents.json, iOS/SecondHand/SecondHand/ColorPalette.swift
=> Ios 35 color 객체 생성

fe/src/App.tsx, fe/src/components/commons/BottomSheet/BottomSheetStyle.ts, fe/src/components/commons/Menu/Menu.stories.ts, fe/src/components/commons/Menu/Menu.tsx, fe/src/components/commons/Menu/MenuStyle.ts, fe/src/components/commons/NavBar/NavBarStyle.ts, fe/src/components/commons/SnackBar/SnackBarStyle.ts, fe/src/components/commons/TextInput/TextInputStyle.ts, fe/src/styles/GlobalStyle.ts, fe/src/styles/Typography.ts, fe/src/styles/styled.d.ts, fe/src/styles/theme.ts
Menu 컴포넌트 구현
https://github.com/second-hand-team-01/second-hand/assets/101160636/04401f45-f2c6-4222-9913-e912d7e6de94
=> [FE] Menu 컴포넌트 구현

fe/.storybook/preview.ts, fe/src/App.tsx, fe/src/components/commons/Layout/Layout.tsx, fe/src/components/commons/Layout/LayoutStyle.ts, fe/src/components/commons/Slide/Slide.tsx, fe/src/components/commons/TabBar/TabBar.tsx, fe/src/constants/routes.tsx, fe/src/services/apis/apis.ts, fe/src/styles/GlobalStyle.ts
페이지 라우터 설정
https://github.com/second-hand-team-01/second-hand/assets/101160636/b3df5325-00c0-42b8-ae68-7dc11eae6f51
* 각 페이지의 경로명은 추후 상의 필요
=> [FE] 페이지 라우터 설정

fe/src/components/commons/Button/Button.tsx, fe/src/components/commons/Button/ButtonStyle.ts, fe/src/components/commons/Dropdown/Dropdown.tsx, fe/src/components/commons/Dropdown/DropdownStyle.ts, fe/src/components/commons/FilterBar/FilterBar.tsx, fe/src/components/commons/FilterBar/FilterBarStyle.ts, fe/src/components/commons/Layout/Layout.tsx, fe/src/components/commons/Layout/LayoutStyle.ts, fe/src/components/commons/Menu/Menu.tsx, fe/src/components/commons/Portal/Portal.tsx, fe/src/components/commons/Portal/PortalStyle.ts, fe/src/mocks/data/items/category-page0.json, fe/src/mocks/data/items/category-page1.json, fe/src/mocks/handlers.ts, fe/src/pages/DetailsPage/DetailsPage.tsx, fe/src/pages/HomePage/CategoryPopup/CategoryElement/CategoryElement.tsx, fe/src/pages/HomePage/CategoryPopup/CategoryElement/CategoryElementStyle.ts, fe/src/pages/HomePage/CategoryPopup/CategoryPopup.tsx, fe/src/pages/HomePage/CategoryPopup/CategoryPopupStyle.ts, fe/src/pages/HomePage/HomePage.tsx, fe/src/pages/WritePage/WritePage.tsx, fe/src/services/apis/apis.ts, fe/src/services/categories/categories.ts, fe/src/services/items/items.ts, fe/src/styles/GlobalStyle.ts, fe/src/type-store/services/category.ts
=> [FE] 52 홈에서 카테고리 버튼을 누르면 오른쪽에서 왼쪽으로

iOS/SecondHand/SecondHand/AccountInfo/AccountInfoViewController.swift, iOS/SecondHand/SecondHand/AccountInfo/UI/AccountInfoView.swift, iOS/SecondHand/SecondHand/Login/LoginViewController.swift
- 로그인시 화면 이동
- 로그인 실패시 알럿 발생
- 로그인 성공시 화면에 아이디 띄우기
- 로그인 성공화면에서 로그아웃 버튼 클릭시 로그인 전 화면으로 이동
=> [iOS]49 - 로그인 수정

fe/src/components/commons/Profile/Profile.tsx, fe/src/pages/LoginPage/LoginPage.tsx, fe/src/pages/SignUpPage/SignUpPage.tsx
=> [FE] 로그인, 회원가입 에러 dialog 처리

fe/src/App.tsx, fe/src/components/commons/FilterBar/FilterBar.tsx, fe/src/components/commons/ImgPreview/ImgElement/ImgElement.tsx, fe/src/components/commons/ImgPreview/ImgPreview.tsx, fe/src/components/commons/LocationPopup/LocationPopup.tsx, fe/src/pages/HomePage/HomePage.tsx, fe/src/pages/LoginPage/LoginPage.tsx, fe/src/pages/SignUpPage/SignUpPage.tsx, fe/src/pages/WritePage/WritePage.tsx, fe/src/services/items/items.ts, fe/src/services/items/write.ts, fe/src/type-store/services/items.ts
=> [FE] 상품 수정에서 이미지 수정 및 상세 페이지 시간 표시

iOS/SecondHand/SecondHand.xcodeproj/project.pbxproj, iOS/SecondHand/SecondHand/Detail/DetailLocalDataSource.swift, iOS/SecondHand/SecondHand/Detail/DetailModel.swift, iOS/SecondHand/SecondHand/Detail/DetailRemoteDataSource.swift, iOS/SecondHand/SecondHand/Detail/DetailRepository.swift, iOS/SecondHand/SecondHand/Detail/DetailUseCase.swift, iOS/SecondHand/SecondHand/Detail/DetailViewController.swift, iOS/SecondHand/SecondHand/Detail/FavoriteResponseDTO.swift, iOS/SecondHand/SecondHand/Detail/UI/DetailContentView.swift, iOS/SecondHand/SecondHand/Detail/UI/DetailToolbar.swift, iOS/SecondHand/SecondHand/Detail/UI/ProductImageViewer.swift, iOS/SecondHand/SecondHand/Extension/Notification+Name.swift, iOS/SecondHand/SecondHand/ItemList/ItemListViewController.swift, iOS/SecondHand/SecondHand/Network/NetworkError.swift
- 상품 좋아요 클릭시 관심상품에 등록 및 해제
- 네트워크에 요청을 보내서 실패시 오류를 발생시킴
- 단뱡향 통신
=> [iOS] 좋아요 버튼 클릭 이벤트 구현

iOS/SecondHand/SecondHand/Detail/UI/DetailViewController.swift, iOS/SecondHand/SecondHand/Edit/UI/EditViewController.swift, iOS/SecondHand/SecondHand/ItemList/Presentation/ItemListPresenter.swift, iOS/SecondHand/SecondHand/ItemList/Presentation/ItemViewModel.swift, iOS/SecondHand/SecondHand/ItemList/View/ItemListTableViewCell.swift, iOS/SecondHand/SecondHand/ItemList/View/PriceLabel.swift
- Model > UI Data 가공 역할의 Presenter 객체 생성
- Presenter에서 전달한 ItemViewModel 기반으로 Snapshot 출력
=> [FIX] iOS - 가격 포맷팅 위치 변경

fe/src/components/commons/InfoBar/InfoBar.tsx, fe/src/components/commons/Layout/LayoutStyle.ts, fe/src/components/commons/ListItem/ListItem.tsx, fe/src/pages/DetailsPage/DetailsPage.tsx, fe/src/services/items/favoriteItems.ts, fe/src/services/items/items.ts, fe/src/stores/UserContext.tsx, fe/src/type-store/services/favoriteItems.ts, fe/src/type-store/services/items.ts, fe/tsconfig.json
=> [FE] 상품 상세 페이지 버그 수정

fe/src/pages/LoginPage/LoginPage.tsx
=> [FE] 로그인 유효성 검사 로직 수정

fe/src/pages/AuthPage/AuthPage.tsx, fe/src/pages/DetailsPage/DetailsPage.tsx, fe/src/pages/HomePage/HomeList/HomeList.tsx, fe/src/pages/LoginPage/LoginPage.tsx, fe/src/pages/SalesHistoryPage/SalesHistoryPage.tsx, fe/src/pages/WritePage/WritePage.tsx, fe/src/stores/UserContext.tsx
* 상품 수정 후 뒤로가기 경로 버그 해결
* 사용자 현재 선택 지역 전역 상태 추가
* 깃헙 로그인시 발생하는 에러 수정
=> Fe 130 사용자는 본인이 등록한 상품의 상태를 변경할 수

fe/src/assets/icons/index.ts, fe/src/components/commons/Carousel/Carousel.tsx, fe/src/components/commons/Carousel/CarouselPageIndicator/CarouselPageIndicator.tsx, fe/src/components/commons/Carousel/CarouselPageIndicator/CarouselPageIndicatorStyle.ts, fe/src/components/commons/Carousel/CarouselStyle.ts, fe/src/components/commons/ListItem/ListItem.tsx, fe/src/components/commons/Menu/Menu.tsx, fe/src/components/commons/index.ts, fe/src/pages/DetailsPage/DetailsPage.tsx, fe/src/pages/SalesHistoryPage/SalesHistoryPage.tsx
- 브라우저 화면에서 다수의 상품 이미지를 볼 수 있도록 캐러셀 기능 추가
- 사용자의 디바이스에 따라, 캐러셀 또는 스와이프 화면 조건부 렌더링
=> [FE] 사용자는 브라우저 화면에서 다수의 상품이미지를 볼 수 있는 기능 구현

fe/package-lock.json, fe/package.json, fe/src/components/commons/Button/ButtonStyle.ts, fe/src/components/commons/Carousel/Carousel.tsx, fe/src/components/commons/ImgPreview/ImgPreview.tsx, fe/src/components/commons/ListItem/ListItem.tsx, fe/src/pages/AuthPage/AuthPage.tsx, fe/src/pages/DetailsPage/DetailsPage.tsx, fe/src/pages/FavoritePage/FavoritePageContents/FavoriteContents.tsx, fe/src/pages/HomePage/HomeList/HomeList.tsx, fe/src/pages/HomePage/HomePage.tsx, fe/src/pages/SalesHistoryPage/SalesHistoryPage.tsx, fe/src/pages/SignUpPage/SignUpPage.tsx, fe/src/pages/WritePage/WritePage.tsx, fe/src/services/apis/apis.ts, fe/src/services/items/items.ts, fe/src/services/items/write.ts, fe/src/services/locations/locations.ts, fe/src/services/signUp/signUp.ts, fe/src/type-store/services/items.ts, fe/src/type-store/services/location.ts, fe/src/type-store/services/signUp.ts
- 상품의 상태 변경(판매중, 예약중, 판매완료) 기능 수정
- 상품 등록 및 수정 페이지 초기 지역 수정
- 상품 수정 페이지 이미지 key 값 UUID 사용
- 전체 지역 조회 API 수정(customFetch 및 useFetch 훅 사용)
=> [FE] 상품의 상태 변경(판매중, 예약중, 판매완료) 기능 수정
